
package gpms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GPMSPort", targetNamespace = "http://gpms.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GPMSPort {


    /**
     * 
     * @param limit
     * @param price
     * @param secretKey
     * @param productName
     * @param introduction
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "publishGroupPurchaseItem", targetNamespace = "http://gpms.ws/", className = "retail.gpms.PublishGroupPurchaseItem")
    @ResponseWrapper(localName = "publishGroupPurchaseItemResponse", targetNamespace = "http://gpms.ws/", className = "retail.gpms.PublishGroupPurchaseItemResponse")
    @Action(input = "http://gpms.ws/GPMSPort/publishGroupPurchaseItemRequest", output = "http://gpms.ws/GPMSPort/publishGroupPurchaseItemResponse")
    public boolean publishGroupPurchaseItem(
            @WebParam(name = "SecretKey", targetNamespace = "")
                    String secretKey,
            @WebParam(name = "productName", targetNamespace = "")
                    String productName,
            @WebParam(name = "introduction", targetNamespace = "")
                    String introduction,
            @WebParam(name = "price", targetNamespace = "")
                    double price,
            @WebParam(name = "limit", targetNamespace = "")
                    int limit);

    /**
     * 
     * @param secretKey
     * @param confirm
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "confirmPurchase", targetNamespace = "http://gpms.ws/", className = "retail.gpms.ConfirmPurchase")
    @ResponseWrapper(localName = "confirmPurchaseResponse", targetNamespace = "http://gpms.ws/", className = "retail.gpms.ConfirmPurchaseResponse")
    @Action(input = "http://gpms.ws/GPMSPort/confirmPurchaseRequest", output = "http://gpms.ws/GPMSPort/confirmPurchaseResponse")
    public boolean confirmPurchase(
            @WebParam(name = "SecretKey", targetNamespace = "")
                    String secretKey,
            @WebParam(name = "confirm", targetNamespace = "")
                    String confirm);

}
